version: '3'
services:
  # Постгрес база в отдельном контейнере
  postgres:
    # Устанавливаем готовый образ
    image: postgres 
    # Задаем глобальные переменные для доступа к PG
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Airflow в отдельном контейнере
  airflow:
    # Сборка из Dockerfile
    build: .
    restart: always
    # Определяет порядок запуска сервисов
    # Будем ждать postgres
    depends_on:
      - postgres
    # Пробрасываем порты
    ports:
      - 8001:8080
    # Пробрасываем папку с дагами
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/root/airflow/plugins
      - logs:/usr/local/airflow/logs
      
        # Jupyter для редактирования DAG и кода
  jupyter:
    image: jupyter/pyspark-notebook:latest
    restart: always
    ports:
      - 32888:8888   # Jupyter
    volumes:
      - ./airflow/dags:/home/jovyan/work/dags
      - ./airflow/plugins:/home/jovyan/work/plugins
      - logs:/home/jovyan/work/logs

volumes:
  pgdata:
  logs: